//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace rejseplanencore.Schemas {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class JourneyDetail {
        
        private Stop[] stopField;
        
        private JourneyName[] journeyNameField;
        
        private JourneyType[] journeyTypeField;
        
        private Note[] noteField;
        
        private JourneyDetailMessage[] messageListField;
        
        private JourneyDetailJourneyChange journeyChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stop")]
        public Stop[] Stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("JourneyName")]
        public JourneyName[] JourneyName {
            get {
                return this.journeyNameField;
            }
            set {
                this.journeyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("JourneyType")]
        public JourneyType[] JourneyType {
            get {
                return this.journeyTypeField;
            }
            set {
                this.journeyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Note")]
        public Note[] Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public JourneyDetailMessage[] MessageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
            }
        }
        
        /// <remarks/>
        public JourneyDetailJourneyChange JourneyChange {
            get {
                return this.journeyChangeField;
            }
            set {
                this.journeyChangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Stop {
        
        private string nameField;
        
        private string routeIdxField;
        
        private string xField;
        
        private string yField;
        
        private string depTimeField;
        
        private string depDateField;
        
        private string arrTimeField;
        
        private string arrDateField;
        
        private string trackField;
        
        private string rtDepTimeField;
        
        private string rtDepDateField;
        
        private string rtArrTimeField;
        
        private string rtArrDateField;
        
        private string rtTrackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdx {
            get {
                return this.routeIdxField;
            }
            set {
                this.routeIdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string depTime {
            get {
                return this.depTimeField;
            }
            set {
                this.depTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string depDate {
            get {
                return this.depDateField;
            }
            set {
                this.depDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arrTime {
            get {
                return this.arrTimeField;
            }
            set {
                this.arrTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arrDate {
            get {
                return this.arrDateField;
            }
            set {
                this.arrDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string track {
            get {
                return this.trackField;
            }
            set {
                this.trackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtDepTime {
            get {
                return this.rtDepTimeField;
            }
            set {
                this.rtDepTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtDepDate {
            get {
                return this.rtDepDateField;
            }
            set {
                this.rtDepDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtArrTime {
            get {
                return this.rtArrTimeField;
            }
            set {
                this.rtArrTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtArrDate {
            get {
                return this.rtArrDateField;
            }
            set {
                this.rtArrDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtTrack {
            get {
                return this.rtTrackField;
            }
            set {
                this.rtTrackField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class JourneyName {
        
        private string nameField;
        
        private string routeIdxFromField;
        
        private string routeIdxToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdxFrom {
            get {
                return this.routeIdxFromField;
            }
            set {
                this.routeIdxFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdxTo {
            get {
                return this.routeIdxToField;
            }
            set {
                this.routeIdxToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class JourneyType {
        
        private JourneyTypeType typeField;
        
        private string routeIdxFromField;
        
        private string routeIdxToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public JourneyTypeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdxFrom {
            get {
                return this.routeIdxFromField;
            }
            set {
                this.routeIdxFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdxTo {
            get {
                return this.routeIdxToField;
            }
            set {
                this.routeIdxToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum JourneyTypeType {
        
        /// <remarks/>
        IC,
        
        /// <remarks/>
        LYN,
        
        /// <remarks/>
        REG,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        TOG,
        
        /// <remarks/>
        BUS,
        
        /// <remarks/>
        EXB,
        
        /// <remarks/>
        NB,
        
        /// <remarks/>
        TB,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        M,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Note {
        
        private string textField;
        
        private string routeIdxFromField;
        
        private string routeIdxToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdxFrom {
            get {
                return this.routeIdxFromField;
            }
            set {
                this.routeIdxFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdxTo {
            get {
                return this.routeIdxToField;
            }
            set {
                this.routeIdxToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class JourneyDetailMessage {
        
        private string headerField;
        
        private string textField;
        
        private JourneyDetailMessageLink[] linksField;
        
        /// <remarks/>
        public string Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Link", IsNullable=false)]
        public JourneyDetailMessageLink[] Links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class JourneyDetailMessageLink {
        
        private string urlField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class JourneyDetailJourneyChange {
        
        private string typeField;
        
        private string routeIdxFromField;
        
        private string routeIdxToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdxFrom {
            get {
                return this.routeIdxFromField;
            }
            set {
                this.routeIdxFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdxTo {
            get {
                return this.routeIdxToField;
            }
            set {
                this.routeIdxToField = value;
            }
        }
    }
}
