//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace rejseplanencore.Schemas {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TripList {
        
        private Trip[] tripField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Trip")]
        public Trip[] Trip {
            get {
                return this.tripField;
            }
            set {
                this.tripField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Trip {
        
        private Leg[] legField;
        
        private RKTariffXML[] rKTariffXMLField;
        
        private bool alternativeField;
        
        private bool validField;
        
        private bool cancelledField;
        
        public Trip() {
            this.alternativeField = false;
            this.validField = true;
            this.cancelledField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Leg")]
        public Leg[] Leg {
            get {
                return this.legField;
            }
            set {
                this.legField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RKTariffXML")]
        public RKTariffXML[] RKTariffXML {
            get {
                return this.rKTariffXMLField;
            }
            set {
                this.rKTariffXMLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool alternative {
            get {
                return this.alternativeField;
            }
            set {
                this.alternativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Leg {
        
        private OriginDestType originField;
        
        private OriginDestType destinationField;
        
        private Notes notesField;
        
        private JourneyDetailRef journeyDetailRefField;
        
        private LegMessage[] messageListField;
        
        private string nameField;
        
        private LegType typeField;
        
        /// <remarks/>
        public OriginDestType Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public OriginDestType Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public Notes Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public JourneyDetailRef JourneyDetailRef {
            get {
                return this.journeyDetailRefField;
            }
            set {
                this.journeyDetailRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public LegMessage[] MessageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LegType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlRootAttribute("Origin", Namespace="", IsNullable=false)]
    public partial class OriginDestType {
        
        private string nameField;
        
        private OriginDestTypeType typeField;
        
        private string routeIdxField;
        
        private string timeField;
        
        private string dateField;
        
        private string trackField;
        
        private string rtTimeField;
        
        private string rtDateField;
        
        private string rtTrackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OriginDestTypeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string routeIdx {
            get {
                return this.routeIdxField;
            }
            set {
                this.routeIdxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string track {
            get {
                return this.trackField;
            }
            set {
                this.trackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtTime {
            get {
                return this.rtTimeField;
            }
            set {
                this.rtTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtDate {
            get {
                return this.rtDateField;
            }
            set {
                this.rtDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtTrack {
            get {
                return this.rtTrackField;
            }
            set {
                this.rtTrackField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum OriginDestTypeType {
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        ADR,
        
        /// <remarks/>
        POI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Notes {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
   
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LegMessage {
        
        private string headerField;
        
        private string textField;
        
        private LegMessageLink[] linksField;
        
        /// <remarks/>
        public string Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Link", IsNullable=false)]
        public LegMessageLink[] Links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LegMessageLink {
        
        private string urlField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum LegType {
        
        /// <remarks/>
        IC,
        
        /// <remarks/>
        LYN,
        
        /// <remarks/>
        REG,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        TOG,
        
        /// <remarks/>
        BUS,
        
        /// <remarks/>
        EXB,
        
        /// <remarks/>
        NB,
        
        /// <remarks/>
        TB,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        WALK,
        
        /// <remarks/>
        BIKE,
        
        /// <remarks/>
        CAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RKTariffXML {
        
        private RKTariffXMLGenericInfotext[] genericField;
        
        private RKTariffXMLPricingSet[] pricingSetField;
        
        private RKTariffXMLError[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("infotext", typeof(RKTariffXMLGenericInfotext), IsNullable=false)]
        public RKTariffXMLGenericInfotext[] generic {
            get {
                return this.genericField;
            }
            set {
                this.genericField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pricingSet")]
        public RKTariffXMLPricingSet[] pricingSet {
            get {
                return this.pricingSetField;
            }
            set {
                this.pricingSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error")]
        public RKTariffXMLError[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RKTariffXMLGenericInfotext {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RKTariffXMLPricingSet {
        
        private RKTariffXMLPricingSetPricing[] pricingField;
        
        private string passengerTypeAmountField;
        
        private string passengerTypeInfoField;
        
        private string passengerTypeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pricing")]
        public RKTariffXMLPricingSetPricing[] pricing {
            get {
                return this.pricingField;
            }
            set {
                this.pricingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string passengerTypeAmount {
            get {
                return this.passengerTypeAmountField;
            }
            set {
                this.passengerTypeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string passengerTypeInfo {
            get {
                return this.passengerTypeInfoField;
            }
            set {
                this.passengerTypeInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string passengerTypeId {
            get {
                return this.passengerTypeIdField;
            }
            set {
                this.passengerTypeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RKTariffXMLPricingSetPricing {
        
        private RKTariffXMLPricingSetPricingTicket[] ticketField;
        
        private string discountLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ticket")]
        public RKTariffXMLPricingSetPricingTicket[] ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string discountLevel {
            get {
                return this.discountLevelField;
            }
            set {
                this.discountLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RKTariffXMLPricingSetPricingTicket {
        
        private string priceField;
        
        private string tariffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]     
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RKTariffXMLError {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
}
